#! /usr/bin/env bash
log(){
	msg="$*"
	echo "$msg" >> /dev/shm/timesync.log
}

restart_ntp_client() {
	ntp_client_service="/etc/init.d/ntpd"
	if [[ -f "$ntp_client_service" ]]; then
		$ntp_client_service restart
	else
		log "/etc/init.d/ntpd not exist, skip"
		exit 127
	fi
}

main() {
	log "sync time now"
	restart_ntp_client
}

main
