#! /usr/bin/bash
set -o pipefail

# Any Error, do exit !!
set -e
set -x

readonly OUTPUT_DIR="${WORKDIR}/output/"
readonly LOG_DIR="${OUTPUT_DIR}/logs/"

readonly TARGET_PLT="$(echo -n "${TARGET}" | cut -d '-' -f1)"
readonly TARGET_ARCH="$(echo -n "${TARGET}" | cut -d '-' -f2)"

if [[ "${TARGET_ARCH}" == arm64 ]]; then
	CROSS_COMPILE="aarch64-linux-gnu-"
fi

if [[ "${TARGET_ARCH}" == x86_64 ]]; then
	CROSS_COMPILE="x86_64-linux-gnu-"
fi

if [[ -f "/usr/bin/${CROSS_COMPILE}strip" ]]; then
	STRIPER="/usr/bin/${CROSS_COMPILE}strip"
else
	echo "/usr/bin/$CROSS_COMPILE-strip" not find !!
	exit 100
fi

MAKE_JOBS="$(nproc)"

build_busybox_static() {
	echo "Enter function: ${FUNCNAME[0]} "

	cd "${WORKDIR}"
	local busybox_src="${OUTPUT_DIR}/busybox"
	local clean_build=false
	local commit_id="1a64f6a20aaf6ea4dbba68bbfa8cc1ab7e5c57c4" # busybox v1.36.1
	local repo="https://git.busybox.net/busybox"
	local busybox_config="${WORKDIR}/configs/x86_64/busybox/busybox-config"

	if [[ -d "${busybox_src}" ]]; then
		echo ""
	else
		git clone "${repo}" "${busybox_src}"
	fi

	cd "${busybox_src}"

	cp "${busybox_config}" "${busybox_src}/.config"

	if [[ -z "${CROSS_COMPILE}" ]]; then
		echo "var CROSS_COMPILE not set, stop !"
		exit 100
	fi

	if [[ "${clean_build}" == "true" ]]; then
		ARCH="${TARGET_ARCH}" CROSS_COMPILE=${CROSS_COMPILE} make -j"$MAKE_JOBS" -C "${busybox_src}" clean
	fi

	ARCH="${TARGET_ARCH}" CROSS_COMPILE=${CROSS_COMPILE} make -j "$MAKE_JOBS" -C "${busybox_src}"

	ARCH="${TARGET_ARCH}" CROSS_COMPILE=${CROSS_COMPILE} make -j "$MAKE_JOBS" -C "${busybox_src}" install
	BUSYBOX_BIN="${busybox_src}/_install/bin/busybox"
	echo "Endof function: ${FUNCNAME[0]} "
}

build_podman() {
	echo "Enter function: ${FUNCNAME[0]} "
	local podman_src="${OUTPUT_DIR}/podman_src"
	local repo="https://github.com/containers/podman"
	local commit_id="bda6eb03dcbcf12a5b7ae004c1240e38dd056d24" # podman v5.1.1

	if [[ -d "${podman_src}" ]]; then
		echo ""
	else

		git clone "${repo}" "${podman_src}"
	fi

	cd "${podman_src}"

	git checkout ${commit_id}
	make podman podman-remote

	if [[ -f bin/podman ]] && [[ -f bin/podman-remote ]]; then
		PODMAN_BIN="${podman_src}/bin/podman"
		PODMAN_REMOTE_BIN="${podman_src}/bin/podman-remote"
		${STRIPER} --strip-unneeded "${PODMAN_BIN}"
		${STRIPER} --strip-unneeded "${PODMAN_REMOTE_BIN}"
	else
		exit 100
	fi

	echo "Endof function: ${FUNCNAME[0]} "
}

get_conmon() {
	wget -c https://github.com/containers/conmon/releases/download/v2.1.12/conmon.amd64 --output-document "${OUTPUT_DIR}/conmon.amd64"
	CONMON="${OUTPUT_DIR}/conmon.amd64"
}

make_netavark() {
	echo "Enter function: ${FUNCNAME[0]} "
	local netavark_src="${OUTPUT_DIR}/netavark_src"
	local repo="https://github.com/containers/netavark"
	local commit_id="ab4f101a39b687c01e2df578162c2fa16a881c1b" # netavark v1.11.0

	if [[ -d "${netavark_src}" ]]; then
		echo ""
	else
		git clone "${repo}" "${netavark_src}"
	fi

	cd "${netavark_src}"
	git checkout "${commit_id}"
	make -j "${MAKE_JOBS}"
	if [[ -f "${netavark_src}/bin/netavark" ]]; then
		NETVAVRK_BIN="${netavark_src}/bin/netavark"
		${STRIPER} --strip-unneeded "${NETVAVRK_BIN}"
	else
		echo "${netavark_src}/bin/netavark NOT FIND"
		exit 100
	fi
	echo "Endof function: ${FUNCNAME[0]} "
}

get_crun() {
	CRUN="${OUTPUT_DIR}/crun-1.15-linux-amd64-disable-systemd"
	local crun_url="https://github.com/containers/crun/releases/download/1.15/crun-1.15-linux-amd64-disable-systemd"
	echo wget -c "${crun_url}" --output-document "${CRUN}"
	wget -c "${crun_url}" --output-document "${CRUN}"
}

pack_deps() {
	echo "Enter function: ${FUNCNAME[0]} "
	touch /tmp/empty
	tar -cvf "${OUTPUT_DIR}/deps.tar" /tmp/empty # create a empty tar file,so that we can add archive files

	{
		IPTABLES_LIBS=()
		IPTABLES_LIBS+=$(ldd /usr/sbin/iptables | grep -v linux-vdso | cut -d '>' -f2 | cut -d '(' -f1)
		IPTABLES_LIBS+=$(ldd /usr/sbin/ip6tables | grep -v linux-vdso | cut -d '>' -f2 | cut -d '(' -f1)
		LIST=${IPTABLES_LIBS[@]}
		for wb in $LIST; do
			tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" "${wb}"
		done
		tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" /usr/lib/x86_64-linux-gnu/xtables
	}

	{
		PODMAN_LIBS=()
		PODMAN_LIBS+=$(ldd ${PODMAN_BIN} | grep -v linux-vdso | cut -d '>' -f2 | cut -d '(' -f1)
		LIST=${PODMAN_LIBS[@]}
		for wb in $LIST; do
			tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" "${wb}"
		done
	}

	{
		NETVAVRK_LIBS=()
		NETVAVRK_LIBS+=$(ldd ${NETVAVRK_BIN} | grep -v linux-vdso | cut -d '>' -f2 | cut -d '(' -f1)
		LIST=${NETVAVRK_LIBS[@]}
		for wb in $LIST; do
			tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" "${wb}"
		done

	}

	{
		tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" /etc/ssl
	}

	{
		mkfsext4_bin="/usr/sbin/mkfs.ext4"
		if [[ -f ${mkfsext4_bin} ]]; then
			LSBLK_LIBS=()
			LSBLK_LIBS+=$(ldd ${mkfsext4_bin} | grep -v linux-vdso | cut -d '>' -f2 | cut -d '(' -f1)
			LSBLK_LIBS+="${mkfsext4_bin}"
		else
			echo "Please apt install util-linux"
			exit 100
		fi
		LIST=$(echo "${LSBLK_LIBS[@]}" | xargs)
		for wb in $LIST; do
			tar --dereference -rvf "${OUTPUT_DIR}/deps.tar" "${wb}"
		done
	}

	echo "Endof function: ${FUNCNAME[0]} "
}

install_deps() {
	if [[ -f "${PODMAN_BIN}" ]] && [[ -f "${NETVAVRK_BIN}" ]] && [[ -f ${CONMON} ]] && [[ -f ${CRUN} ]]; then
		mkdir -p "${ovmrootfs}/usr/libexec/podman/"

		echo cp -rf "${CONMON}" "${ovmrootfs}/usr/libexec/podman/conmon"
		cp -rf "${CONMON}" "${ovmrootfs}/usr/libexec/podman/conmon"

		echo cp -rf "${CRUN}" "${ovmrootfs}/usr/bin/crun"
		cp -rf "${CRUN}" "${ovmrootfs}/usr/bin/crun"

		echo cp -rf "${NETVAVRK_BIN}" "${ovmrootfs}/usr/libexec/podman/netavark"
		cp -rf "${NETVAVRK_BIN}" "${ovmrootfs}/usr/libexec/podman/netavark"

		echo cp "${PODMAN_BIN}" "${ovmrootfs}/usr/bin/podman"
		cp "${PODMAN_BIN}" "${ovmrootfs}/usr/bin/podman"

		chmod +x "${ovmrootfs}/usr/bin/podman"
		chmod +x "${ovmrootfs}/usr/bin/crun"
		chmod +x "${ovmrootfs}/usr/libexec/podman/conmon"
		chmod +x "${ovmrootfs}/usr/libexec/podman/netavark"

		cp /usr/sbin/iptables ${ovmrootfs}/usr/bin/
		cp /usr/sbin/ip6tables ${ovmrootfs}/usr/bin/

		cd ${ovmrootfs}
		tar -xvf "${OUTPUT_DIR}/deps.tar" -C ./

		cp -r /etc/ld.so* "${ovmrootfs}/etc/"
		cp ${WORKDIR}/scripts/ovmd ${ovmrootfs}/opt/ovmd
		chmod +x ${ovmrootfs}/opt/ovmd
	else
		exit 100
	fi
}

write_podman_config() {

	mkdir -p "${ovmrootfs}/etc/containers"
	cp "${OUTPUT_DIR}/podman_src/pkg/machine/ocipull/policy.json" "${ovmrootfs}/etc/containers/policy.json"
	echo '
unqualified-search-registries = ["docker.io", "quay.io", "registry.fedoraproject.org"]

[[registry]]
location = "docker.io"
prefix = "docker.io"
mirror-by-digest-only = true
insecure = false

[[registry]]
location = "quay.io"
prefix = "quay.io"
mirror-by-digest-only = false
insecure = false
		' >"${ovmrootfs}/etc/containers/registries.conf"

	echo '
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ]
}
' >"${ovmrootfs}/etc/containers/policy.json"

}

make_wsl_rootfs() {
	cd "${WORKDIR}"
	echo "Enter function: ${FUNCNAME[0]} "
	local ovmrootfs_version="v1.0"
	fakeroot="${OUTPUT_DIR}/ovmrootfs_fakeroot"                                  # Absolute path !
	ovmrootfs="${fakeroot}/opt/ovmcorefilesystem/ovmrootfs_${ovmrootfs_version}" # Absolute path !

	rm -rf "${fakeroot}"

	mkdir -p "${ovmrootfs}/usr/lib/x86_64-linux-gnu/xtables"
	mkdir -p "${ovmrootfs}/usr/lib/wsl/drivers"
	mkdir -p "${ovmrootfs}/mnt/wslg/distro"
	mkdir -p "${ovmrootfs}/usr/lib/modules"
	mkdir -p "${ovmrootfs}/usr/lib/wsl/lib"
	mkdir -p "${ovmrootfs}/mnt/wslg/doc"
	mkdir -p "${ovmrootfs}/usr/lib64"
	mkdir -p "${ovmrootfs}/usr/bin"
	mkdir -p "${ovmrootfs}/etc"
	mkdir -p "${ovmrootfs}/home"
	mkdir -p "${ovmrootfs}/root"
	mkdir -p "${ovmrootfs}/opt"
	mkdir -p "${ovmrootfs}/var/tmp"

	cp "${BUSYBOX_BIN}" "${ovmrootfs}/usr/bin"
	cd "${ovmrootfs}/usr/bin"
	echo "Install Busybox into ${ovmrootfs}"
	./busybox --install ./

	cd "${ovmrootfs}"
	ln -s usr/bin bin
	ln -s usr/lib lib
	ln -s usr/lib64 lib64

	{
		echo "We are in $(pwd)"
		echo "Create soft-link : opt/ovmcorefilesystem/ovmrootfs_${ovmrootfs_version} => ovmrootfs_current"
		cd "${fakeroot}"
		ln -sf -r "opt/ovmcorefilesystem/ovmrootfs_${ovmrootfs_version}" "ovmrootfs_current"

		dirs=$(busybox ls "ovmrootfs_current/")

		for d in ${dirs}; do
			echo ln -sf "ovmrootfs_current/${d}" ./"${d}"
			ln -sf "ovmrootfs_current/${d}" ./"${d}"
		done
	}

	OVMCORE_FS="${ovmrootfs}"   # Absolute path !
	OVMCORE_OTAFS="${fakeroot}" # Absolute path !

	echo "Endof function: ${FUNCNAME[0]} "
}

pack_ovmfs() {
	cd ${ovmrootfs}
	tar -Jcvf "${OUTPUT_DIR}/ovmrootfs.tar.xz" $(ls .)

	cd ${fakeroot}
	tar -Jcvf "${OUTPUT_DIR}/ovmrootfs_ota.tar.xz" $(ls .)
}

main() {
	# CALLER_ID make sure script called from make, not by others.
	if [[ "${CALLER_ID}" = "d9b59105e7569a37713aeadb493ca01a3779747f" ]]; then
		cd "$WORKDIR"
		build_busybox_static
		build_podman
		make_netavark
		get_conmon
		get_crun
		make_wsl_rootfs
		pack_deps
		install_deps
		write_podman_config
		pack_ovmfs

		echo '================================='
		echo OVMCORE_ROOTFS="${OVMCORE_FS}"
		echo OVMCORE_ROOTFS_ARCHIVE="${OUTPUT_DIR}/ovmrootfs.tar.xz"
		echo OVMCORE_OTAFS="${OVMCORE_OTAFS}"
		echo OVMCORE_OTAFS_ARCHIVE="${OUTPUT_DIR}/ovmrootfs_ota.tar.xz"
		echo BUSYBOX_BIN="${BUSYBOX_BIN}"
		echo PODMAN="${PODMAN_BIN}"
		echo PODMAN_REMOTE_BIN="${PODMAN_REMOTE_BIN}"
		echo '================================='
	else
		exit 1
	fi
}

main
