#! /usr/bin/env bash
if [[ $SKIP_APT_GET_INSTALL == "true" ]]; then
	echo '$SKIP_APT_GET_INSTALL == true, skip install required package'
else
	sudo -E apt update && sudo -E apt -y install wget kpartx zstd || {
		echo "Error: Install wget failed"
		exit 100
	}
fi

# one package one line
preinstalled_packages="
	bash
	podman
	dmesg
	procps
	findmnt
	blkid
	mount
	tar
	zstd
	"
rootfs_url=""
bootable_url="https://github.com/oomol/builded/releases/download/v1.1/alpine_uefi_bootable.img.zst"
# the alpine_uefi_bootable.img.zst has ROOTFS and EFI partition
rootfs_part_uuid="d1e46927-eb5d-4fbf-986a-7e5581f37a16"
efi_part_uuid="6729-82AB"

# file_name:sha1sum
sha1sum="cceb5153fa0bc45dc921494af35e4d61543dfbe5  alpine_uefi_bootable.img.zst"

bootstrap_alpine() {
	set -x
	rm -rf "$output/alpine_uefi_bootable.img.zst"
	wget -c "$bootable_url" --output-document="$output/alpine_uefi_bootable.img.zst" --output-file=/tmp/log_download_alpine_uefi_bootable.img.txt
	set +x
	echo "$sha1sum" >$output/alpine_uefi_bootable.img.zst.sha1sum

	cd $output && sha1sum -c alpine_uefi_bootable.img.zst.sha1sum || {
		echo "Error: checksha1sum failed"
		exit 100
	} && cd $workspace

	cd $output && {
		# Decompress alpine_uefi_bootable.img.zst
		zstd -d -f alpine_uefi_bootable.img.zst || {
			echo "Decompress alpine_uefi_bootable.img.zst failed"
			exit 100
		}
		# Mapping the part into /dev/mapper/loopNpN
		kpartx -av alpine_uefi_bootable.img &&
			mount -m -U $rootfs_part_uuid ./target_rootfs &&
			mount -m -U $efi_part_uuid ./target_rootfs/boot/efi || {
			echo "Error: Mount alpine_uefi_bootable.img failed"
			exit 100
		}
	} && cd $workspace

	cd $output && {
		# Podman live in http://dl-cdn.alpinelinux.org/alpine/v3.20/community
		echo http://dl-cdn.alpinelinux.org/alpine/v3.20/community >>target_rootfs/etc/apk/repositories
	} && cd $workspace

	# set qemu_flag if CROSS_BUILD
	if [[ $CROSS_BUILD == true ]]; then
		qemu_flag='--qemu=qemu-aarch64-static'
	else
		qemu_flag=''
	fi

	# Install required package into rootfs
	pkgs=$(echo $preinstalled_packages | xargs)
	set -x
	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c "apk update;apk add $pkgs" || {
			echo "Error: proot into rootfs failed"
			exit 100
		}
	} && cd $workspace
	set +x

	echo "Generat ssh keys and copy into rootfs"
	set -x
	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c 'rm -rf /root/.ssh/ovm_id && ssh-keygen  -f /root/.ssh/ovm_id  -N "" && cat /root/.ssh/ovm_id.pub >> /root/.ssh/authorized_keys' || {
			echo "Error: proot into rootfs failed"
			exit 100
		}
	} && cd $workspace

	sudo -E rm -rf /tmp/ovm_ssh
	sudo -E cp -rf $output/target_rootfs/root/.ssh /tmp/ovm_ssh
	set +x
	sync

	set -x
	cd $workspace && sudo -E umount -R $output/target_rootfs || {
		echo "Error: umount $output/target_rootfs failed"
	}
	set +x
}
copy_layer() {
	echo "INFO: Copy $target_profile layers files"
	export VM_CONSOLE_DEVICE=hvc0
	cd $workspace || {
		echo 'Error: change dir to $workspace failed'
		exit 100
	}

	set -x
	cd ./layers/$target_profile && {
		# Now we are in ./layers/$target_profile
		find ./ -type f -exec sed -i.bak 's/VM_CONSOLE_DEVICE/hvc0/g' {} + # Replace VM_CONSOLE_DEVICE to hvc0
		cp -rf ./* "$output/$target_rootfs" || {
			echo "Copy layer into $output/$target_rootfs failed"
			exit 100
		}
	} || {
		echo 'Error: change dir to ./layers/$target_profile failed'
		exit 100
	} && cd $workspace
	set +x
}

pack_rootfs() {
	set -x
	cd $output && {
		zstd --force -16 alpine_uefi_bootable.img || {
			echo "Error: Compress alpine_uefi_bootable.img failed"
			exit 100
		}
	} && cd $workspace
	set +x
}

echo "=== Bootstrap Alpine ==="
if [[ -z $workspace ]] && [[ -z $output ]]; then
	echo 'Error: $workspace or $output empty'
	exit 100
fi

echo workspace: $workspace
echo output: $output
bootstrap_alpine
copy_layer
pack_rootfs
