#! /usr/bin/env bash
if [[ $SKIP_APT_GET_INSTALL == "true" ]]; then
	echo '$SKIP_APT_GET_INSTALL == true, skip install required package'
else
	sudo -E apt update && sudo -E apt -y install wget kpartx zstd || {
		echo "Error: Install wget failed"
		exit 100
	}
fi

# one package one line
preinstalled_packages="
	bash
	podman
	dmesg
	procps
	findmnt
	blkid
	mount
	tar
	zstd
	tzdata
	"
rootfs_url=""
bootable_url="https://github.com/oomol/builded/releases/download/v1.5/alpine_uefi_bootable-x86_64.img.zst"
sha1sum="fc62a59289a3f4721bb7d44730ca5a631c592531"
# the alpine_uefi_bootable.img.zst has ROOTFS and EFI partition
rootfs_part_uuid="1db9dd50-085d-4d38-a911-ea4446d29875"
efi_part_uuid="4cc17f62-ab8d-4593-b787-8a7bffd6b1ad"
bootable_file_zst="alpine_uefi_bootable.img.zst"

clean_mapping() {
	umount -R $output/target_rootfs >/dev/null 2>&1
	# Clean kpartx mapping devices
	sudo -E losetup -a | grep alpine_uefi_bootable.img | cut -d ':' -f1 | while read -r item; do sudo -E kpartx -dv $item; done && {
		sudo -E losetup -D
	} || {
		echo "Clean kpartx mapping failed"
		exit 100
	}
}

bootstrap_alpine() {
	bootable_file="${bootable_file_zst%.*}"
	sha1sum_file="${bootable_file_zst}.sha1sum"

	set -x
	sudo -E rm -rf "$output/${bootable_file_zst}"
	wget -c "$bootable_url" --output-document="$output/${bootable_file_zst}" --output-file=/tmp/log_download_alpine_uefi_bootable.img.txt
	set +x

	echo "$sha1sum ${bootable_file_zst}" >"$output/${sha1sum_file}"
	cd $output && sha1sum -c "${sha1sum_file}" || {
		echo "Error: checksha1sum failed"
		exit 100
	} && cd $workspace

	cd $output && {
		# Decompress alpine_uefi_bootable.img.zst
		zstd -d -f "${bootable_file_zst}" || {
			echo "Decompress ${bootable_file_zst} failed"
			exit 100
		}
		# Mapping the part into /dev/mapper/loopNpN
		kpartx -av ${bootable_file} &&
			mount -m -U $rootfs_part_uuid ./target_rootfs &&
			mount -m -U $efi_part_uuid ./target_rootfs/boot || {
			echo "Error: Mount alpine_uefi_bootable.img failed"
			exit 100
		}
	} && cd $workspace

	cd $output && {
		# Podman live in http://dl-cdn.alpinelinux.org/alpine/v3.20/community
		echo http://dl-cdn.alpinelinux.org/alpine/v3.20/community >>target_rootfs/etc/apk/repositories
	} && cd $workspace

	# set qemu_flag if CROSS_BUILD
	if [[ $CROSS_BUILD == true ]]; then
		qemu_flag="--qemu=$output/qemu_bins/static_qemu/bin/qemu-x86_64"
	else
		qemu_flag=''
	fi

	# Install required package into rootfs
	pkgs=$(echo $preinstalled_packages | xargs)
	set -x
	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c "apk update;apk add $pkgs" || {
			echo "Error: proot into rootfs failed"
			exit 100
		}
	} && cd $workspace
	set +x

	echo "Generat ssh keys and copy into rootfs"
	set -x
	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c 'rm -rf /root/.ssh/ovm_id && ssh-keygen  -f /root/.ssh/ovm_id  -N "" && cat /root/.ssh/ovm_id.pub >> /root/.ssh/authorized_keys' || {
			echo "Error: proot into rootfs failed"
			exit 100
		}
	} && cd $workspace

	sudo -E rm -rf /tmp/ovm_ssh
	sudo -E cp -rf $output/target_rootfs/root/.ssh /tmp/ovm_ssh
	set +x
	sync
}
copy_layer() {
	echo "INFO: Copy $target_profile layers files"
	export VM_CONSOLE_DEVICE=hvc0
	cd $workspace || {
		echo 'Error: change dir to $workspace failed'
		exit 100
	}

	set -x
	cd ./layers/$target_profile && {
		if [[ ${VM_PROVIDER} == "qemu" ]]; then
			find ./ -type f -exec sed -i 's/VM_CONSOLE_DEVICE/ttyAMA0/g' {} + # Replace VM_CONSOLE_DEVICE to ttyAMA0
		else
			find ./ -type f -exec sed -i 's/VM_CONSOLE_DEVICE/hvc0/g' {} + # Replace VM_CONSOLE_DEVICE to hvc0
		fi
		sudo -E cp -rf ./* "$output/target_rootfs" || {
			echo "Copy layer into $output/$target_rootfs failed"
			exit 100
		}
	} || {
		echo 'Error: change dir to ./layers/$target_profile failed'
		exit 100
	} && cd $workspace

	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c "chmod +x /etc/init.d/ovmservice && 
			rc-update add ovmservice default &&
			rc-update del networking boot && 
			rc-update add networking default &&
		       	rc-update add podman default" || {
			echo "Error: add ovmservice into default stage failed"
			exit 100
		}
	} && cd $workspace

	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c "echo rc_parallel=YES >> /etc/rc.conf" || {
			echo "Error: enable rc_parallel failed"
			exit 100
		}
	} && cd $workspace

	cd $output && {
		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
			-b /dev:/dev \
			-b /sys:/sys \
			-b /proc:/proc \
			-b /etc/resolv.conf:/etc/resolv.conf \
			-w /root \
			-0 /bin/su -c "touch /.first_boot" || {
			echo "Error: enable rc_parallel failed"
			exit 100
		}
	} && cd $workspace

	set +x
	sync # must do sync !
}

umount_rootfs() {
	cd $output && {
		umount -R ./target_rootfs
	} || {
		echo "Error: failed to umount $output/target_rootfs"
		exit 100
	}
	cd $workspace || {
		echo "Change dir to  workspace failed"
		exit 100
	}
}

pack_rootfs() {
	cd $output && {
		zstd --force alpine_uefi_bootable.img && {
			sha1sum alpine_uefi_bootable.img.zst >alpine_uefi_bootable.img.zst.sha1sum
		} || {
			echo "Error: Compress alpine_uefi_bootable.img failed"
			exit 100
		}
	}

	cd "$workspace" || {
		echo "Change dir to  workspace failed"
		exit 100
	}
}

bootimage() {
	cd "$workspace" || {
		echo "Failed to change dir to workspace"
		exit 100
	}
	bash +x ./subfunc/boot_raw_disk.sh "$output/$bootable_file" x86_64 || {
		echo "Error: boot $output/$bootable_file failed"
		exit 100
	}
}

echo "=== Bootstrap Alpine ==="
if [[ -z $workspace ]] && [[ -z $output ]]; then
	echo 'Error: $workspace or $output empty'
	exit 100
fi

echo "workspace: $workspace"
echo "output: $output"
clean_mapping
bootstrap_alpine
#copy_layer
umount_rootfs
clean_mapping
bootimage >/tmp/vm_boot_log 2>&1 &
tail -f /tmp/vm_boot_log &
while true; do
	ssh -o ConnectTimeout=1 -o StrictHostKeyChecking=no -i /tmp/ovm_ssh/ovm_id root@127.0.0.1 -p10025 "update-grub && sync && halt" && {
		echo Update-grub successful
		break
	} || {
		echo "Try ssh into vm again..."
		sleep 2
		continue
	}
done
pack_rootfs
