name: Build WSL2 Profile
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
env:
  CI_ENV: IN_CI

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Build
        run: |
          sudo -E ./make wsl2_amd64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-amd64.zst
          path: |
            output/rootfs-amd64.zst
            output/rootfs-amd64.zst.sha256sum
          if-no-files-found: error
          overwrite: true
